### ISSUE TITLE
Exec external commands

### ISSUE THREAD

**Issue by jacobaraujo7** [pingbird/puro#26]
There are some other CLIs that run Flutter commands internally.
A good example for this is Melos, which by using "melos bs" calls `flutter pub get` on all configured packages.
My suggestion would be to add a new command to `Puro` that runs the command in the project environment.

Today I do it like this:
```
puro use -g my_env
melos bs
```

Suggestion:
```
puro exec melos bs
```

**Comment by pingbird** [comment]
melos is installed through `pub global activate` which can only be done in the global default environment because the script it creates uses `dart` from the PATH.

Unfortunately there is nothing I can do to tell melos what version to use when doing a pub get other than set the PATH which would break the script.

**Comment by pingbird** [comment]
I think a reasonable long term solution would be to replace `pub global activate` with one that creates scripts that invoke puro

**Comment by pingbird** [comment]
Moving to #36
