### ISSUE TITLE
Puro recommends removing the .bat files

### ISSUE THREAD

**Issue by BrunoVieiraOneSystem** [pingbird/puro#81]
puro upgrade-puro
[!] Other Flutter or Dart installations detected
    Puro recommends removing the following from your PATH:
    * C:\Users\bruno\.puro\envs\one_comercial\flutter\bin\dart.bat
    * C:\tools\flutter\bin\dart.bat
    * C:\Users\bruno\.puro\envs\one_comercial\flutter\bin\flutter.bat
    * C:\tools\flutter\bin\flutter.bat
[✓] Successfully installed Puro 1.4.6 to `C:\Users\bruno\.puro`

after remove the files, the projecto don't execute

'"C:\Users\bruno\.puro\envs\one_comercial\flutter\bin\flutter.bat"' n�o � reconhecido como um comando interno
ou externo, um programa oper�vel ou um arquivo em lotes.
Exited (1)

**Comment by pingbird** [comment]
You aren't supposed to delete the files, just remove the parent directory from the PATH environment variable, puro adds `.puro\envs\default` and manages where it points to itself. I believe `C:\Users\bruno.puro\envs\one_comercial\flutter\bin` is showing up because it was added manually at some point, that entry can be safely removed from the PATH.
